// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClOSI1yJ-GlgPdVj53Bn2HuBKTZ0wJI3w',
    appId: '1:865501550689:web:27b91fcb939e317f09b220',
    messagingSenderId: '865501550689',
    projectId: 'ecotech-8443c',
    authDomain: 'ecotech-8443c.firebaseapp.com',
    databaseURL: 'https://ecotech-8443c-default-rtdb.firebaseio.com',
    storageBucket: 'ecotech-8443c.appspot.com',
    measurementId: 'G-8CQXEVHKB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCvo7r-m7E2JjMK-9MY38bzUHJ6yZi5Gk',
    appId: '1:865501550689:android:37ade269f208531109b220',
    messagingSenderId: '865501550689',
    projectId: 'ecotech-8443c',
    databaseURL: 'https://ecotech-8443c-default-rtdb.firebaseio.com',
    storageBucket: 'ecotech-8443c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUz9J6swnSefGLv3hclhXkwcSmhX1LACI',
    appId: '1:865501550689:ios:d3473e6962bf404b09b220',
    messagingSenderId: '865501550689',
    projectId: 'ecotech-8443c',
    databaseURL: 'https://ecotech-8443c-default-rtdb.firebaseio.com',
    storageBucket: 'ecotech-8443c.appspot.com',
    androidClientId: '865501550689-8l6e3f7rpcjooagmt5s8bisf00u2d7ip.apps.googleusercontent.com',
    iosClientId: '865501550689-anv9ddgbudvtbisttpqp6ea42l2iheiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecotech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUz9J6swnSefGLv3hclhXkwcSmhX1LACI',
    appId: '1:865501550689:ios:d3473e6962bf404b09b220',
    messagingSenderId: '865501550689',
    projectId: 'ecotech-8443c',
    databaseURL: 'https://ecotech-8443c-default-rtdb.firebaseio.com',
    storageBucket: 'ecotech-8443c.appspot.com',
    androidClientId: '865501550689-8l6e3f7rpcjooagmt5s8bisf00u2d7ip.apps.googleusercontent.com',
    iosClientId: '865501550689-anv9ddgbudvtbisttpqp6ea42l2iheiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecotech',
  );
}
